// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQBW5GpTjul00-en3l4ibmDTSTYMmeWSU',
    appId: '1:1069962099477:web:dfd648c24db62423ab871c',
    messagingSenderId: '1069962099477',
    projectId: 'resq-594df',
    authDomain: 'resq-594df.firebaseapp.com',
    storageBucket: 'resq-594df.firebasestorage.app',
    measurementId: 'G-NX6KJVLFHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDsyJLTiDzMbQNyqpGeus8iKAdXhvgu2g',
    appId: '1:1069962099477:android:33ae9b7fc3cd9624ab871c',
    messagingSenderId: '1069962099477',
    projectId: 'resq-594df',
    storageBucket: 'resq-594df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjfcUzTJjRESKZRXJfICsA72ZS64YkV4E',
    appId: '1:1069962099477:ios:000d77fc245dce83ab871c',
    messagingSenderId: '1069962099477',
    projectId: 'resq-594df',
    storageBucket: 'resq-594df.firebasestorage.app',
    iosBundleId: 'com.example.projct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjfcUzTJjRESKZRXJfICsA72ZS64YkV4E',
    appId: '1:1069962099477:ios:000d77fc245dce83ab871c',
    messagingSenderId: '1069962099477',
    projectId: 'resq-594df',
    storageBucket: 'resq-594df.firebasestorage.app',
    iosBundleId: 'com.example.projct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQBW5GpTjul00-en3l4ibmDTSTYMmeWSU',
    appId: '1:1069962099477:web:575713b7a48fdd98ab871c',
    messagingSenderId: '1069962099477',
    projectId: 'resq-594df',
    authDomain: 'resq-594df.firebaseapp.com',
    storageBucket: 'resq-594df.firebasestorage.app',
    measurementId: 'G-YN9JY2622H',
  );
}
